var Api = [{
        id: 1,
        img: "https://picsum.photos/200",
        title: "honim",
        price: 2.3,
        type: "hotdishes",
        available:"11 Bowls available",
    },
    {
        id: 2,
        img: "https://picsum.photos/200",
        title: "jarkop",
        price: 2,
        type: "cold-dishes",
        available:"11 Bowls available",
    },
    {
        id: 3,
        img: "https://picsum.photos/200",
        title: "shorva",
        price: 4,
        type: "cold-dishes",
        available:"11 Bowls available",
    },
    {
        id: 4,
        img: "https://picsum.photos/200",
        title: "mastava",
        price: 4.3,
        type: "soup",
        available:"11 Bowls available",
    },
    {
        id: 5,
        img: "https://picsum.photos/200",
        title: "palov",
        price: 0.9,
        type: "soup",
        available:"11 Bowls available",
    },
    {
        id: 6,
        img: "https://picsum.photos/200",
        title: "norin",
        price: 3.3,
        type: "soup",
        available:"11 Bowls available",
    },
    {
        id: 7,
        img: "https://picsum.photos/200",
        title: "manti",
        price: 1.3,
        type: "grill",
        available:"11 Bowls available",
    },
    {
        id: 8,
        img: "https://picsum.photos/200",
        title: "lagmin",
        price: 2.8,
        type: "dessert",
        available:"11 Bowls available",
    },
    {
        id: 9,
        img: "https://picsum.photos/200",
        title: "honim",
        price: 2.3,
        type: "hotdishes",
        available:"11 Bowls available",
    },
    {
        id: 10,
        img: "https://picsum.photos/200",
        title: "jarkop",
        price: 2,
        type: "cold-dishes",
        available:"11 Bowls available",
    },
    {
        id: 11,
        img: "https://picsum.photos/200",
        title: "shorva",
        price: 4,
        type: "cold-dishes",
        available:"11 Bowls available",
    },
    {
        id: 12,
        img: "https://picsum.photos/200",
        title: "mastava",
        price: 4.3,
        type: "soup",
        available:"11 Bowls available",
    },
    {
        id: 13,
        img: "https://picsum.photos/200",
        title: "palov",
        price: 0.9,
        type: "soup",
        available:"11 Bowls available",
    },
    {
        id: 14,
        img: "https://picsum.photos/200",
        title: "norin",
        price: 3.3,
        type: "soup",
        available:"11 Bowls available",
    },
    {
        id: 15,
        img: "https://picsum.photos/200",
        title: "manti",
        price: 1.3,
        type: "grill",
        available:"11 Bowls available",
    },
    {
        id: 16,
        img: "https://picsum.photos/200",
        title: "lagmin",
        price: 2.8,
        type: "dessert",
        available:"11 Bowls available",
    },
    {
        id: 17,
        img: "https://picsum.photos/200",
        title: "honim",
        price: 2.3,
        type: "hotdishes",
        available:"11 Bowls available",
    },
    {
        id: 18,
        img: "https://picsum.photos/200",
        title: "jarkop",
        price: 2,
        type: "cold-dishes",
        available:"11 Bowls available",
    },
    {
        id: 19,
        img: "https://picsum.photos/200",
        title: "shorva",
        price: 4,
        type: "cold-dishes",
        available:"11 Bowls available",
    },
    {
        id: 20,
        img: "https://picsum.photos/200",
        title: "mastava",
        price: 4.3,
        type: "soup",
        available:"11 Bowls available",
    },
    {
        id: 21,
        img: "https://picsum.photos/200",
        title: "palov",
        price: 0.9,
        type: "soup",
        available:"11 Bowls available",
    },
    {
        id: 22,
        img: "https://picsum.photos/200",
        title: "norin",
        price: 3.3,
        type: "soup",
        available:"11 Bowls available",
    },
    {
        id: 23,
        img: "https://picsum.photos/200",
        title: "manti",
        price: 1.3,
        type: "grill",
        available:"11 Bowls available",
    },
    {
        id: 24,
        img: "https://picsum.photos/200",
        title: "lagmin",
        price: 2.8,
        type: "dessert",
        available:"11 Bowls available",
    },
]
export default Api;